# Here we include the actual data cleaning part for our training data, such that it is easily accessible

## All graphs for everything can be found in dataCleaning.ipynb and test.ipynb

Loading Libraries and dataset

In [2]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns
df = pd.read_csv("claims_train.csv")
df

,IDpol,ClaimNb,Exposure,Area,VehPower,VehAge,DrivAge,BonusMalus,VehBrand,VehGas,Density,Region
0,2122523.0,0,0.43,D,7,18,36,95,B1,Regular,1054,R24
1,3173420.0,0,0.10,D,7,17,80,95,B2,Regular,598,R25
2,1188619.0,0,0.33,E,7,3,36,76,B6,Regular,4172,R82
3,31400.0,0,0.56,A,5,4,73,52,B13,Diesel,15,R24
4,3138755.0,0,0.27,E,8,0,37,50,B11,Diesel,3021,R53
...,...,...,...,...,...,...,...,...,...,...,...,...
542405,2063494.0,0,0.20,D,6,10,32,76,B2,Diesel,1314,R24
542406,4164964.0,0,0.06,D,10,14,34,60,B5,Diesel,685,R72
542407,3078112.0,0,0.34,C,6,8,32,95,B5,Diesel,242,R82
542408,1012927.0,0,0.72,E,9,7,39,72,B2,Regular,3301,R73
542409,170144.0,0,0.59,A,7,18,41,106,B1,Regular,26,R24

Removal of IDPol feature

In [3]:
df = df.drop(columns=["IDpol"])

Removing Exposure values above 1

In [4]:
exposureMask = df["Exposure"] <= 1
df = df[exposureMask]
df

,ClaimNb,Exposure,Area,VehPower,VehAge,DrivAge,BonusMalus,VehBrand,VehGas,Density,Region
0,0,0.43,D,7,18,36,95,B1,Regular,1054,R24
1,0,0.10,D,7,17,80,95,B2,Regular,598,R25
2,0,0.33,E,7,3,36,76,B6,Regular,4172,R82
3,0,0.56,A,5,4,73,52,B13,Diesel,15,R24
4,0,0.27,E,8,0,37,50,B11,Diesel,3021,R53
...,...,...,...,...,...,...,...,...,...,...,...
542405,0,0.20,D,6,10,32,76,B2,Diesel,1314,R24
542406,0,0.06,D,10,14,34,60,B5,Diesel,685,R72
542407,0,0.34,C,6,8,32,95,B5,Diesel,242,R82
542408,0,0.72,E,9,7,39,72,B2,Regular,3301,R73
542409,0,0.59,A,7,18,41,106,B1,Regular,26,R24

Removing Vehicle Age values above 40

In [5]:
vehicleAgeMask = df["VehAge"] <= 40
df = df[vehicleAgeMask]
df

,ClaimNb,Exposure,Area,VehPower,VehAge,DrivAge,BonusMalus,VehBrand,VehGas,Density,Region
0,0,0.43,D,7,18,36,95,B1,Regular,1054,R24
1,0,0.10,D,7,17,80,95,B2,Regular,598,R25
2,0,0.33,E,7,3,36,76,B6,Regular,4172,R82
3,0,0.56,A,5,4,73,52,B13,Diesel,15,R24
4,0,0.27,E,8,0,37,50,B11,Diesel,3021,R53
...,...,...,...,...,...,...,...,...,...,...,...
542405,0,0.20,D,6,10,32,76,B2,Diesel,1314,R24
542406,0,0.06,D,10,14,34,60,B5,Diesel,685,R72
542407,0,0.34,C,6,8,32,95,B5,Diesel,242,R82
542408,0,0.72,E,9,7,39,72,B2,Regular,3301,R73
542409,0,0.59,A,7,18,41,106,B1,Regular,26,R24

Removing Driver Age Values above 92

In [6]:
driverAgeMask = df["DrivAge"] <= 92
df = df[driverAgeMask]
df

,ClaimNb,Exposure,Area,VehPower,VehAge,DrivAge,BonusMalus,VehBrand,VehGas,Density,Region
0,0,0.43,D,7,18,36,95,B1,Regular,1054,R24
1,0,0.10,D,7,17,80,95,B2,Regular,598,R25
2,0,0.33,E,7,3,36,76,B6,Regular,4172,R82
3,0,0.56,A,5,4,73,52,B13,Diesel,15,R24
4,0,0.27,E,8,0,37,50,B11,Diesel,3021,R53
...,...,...,...,...,...,...,...,...,...,...,...
542405,0,0.20,D,6,10,32,76,B2,Diesel,1314,R24
542406,0,0.06,D,10,14,34,60,B5,Diesel,685,R72
542407,0,0.34,C,6,8,32,95,B5,Diesel,242,R82
542408,0,0.72,E,9,7,39,72,B2,Regular,3301,R73
542409,0,0.59,A,7,18,41,106,B1,Regular,26,R24

Removing bonus-malus scores greater than 160

In [7]:
bonusMalusMask = df["BonusMalus"] <= 160
df = df[bonusMalusMask]
df

,ClaimNb,Exposure,Area,VehPower,VehAge,DrivAge,BonusMalus,VehBrand,VehGas,Density,Region
0,0,0.43,D,7,18,36,95,B1,Regular,1054,R24
1,0,0.10,D,7,17,80,95,B2,Regular,598,R25
2,0,0.33,E,7,3,36,76,B6,Regular,4172,R82
3,0,0.56,A,5,4,73,52,B13,Diesel,15,R24
4,0,0.27,E,8,0,37,50,B11,Diesel,3021,R53
...,...,...,...,...,...,...,...,...,...,...,...
542405,0,0.20,D,6,10,32,76,B2,Diesel,1314,R24
542406,0,0.06,D,10,14,34,60,B5,Diesel,685,R72
542407,0,0.34,C,6,8,32,95,B5,Diesel,242,R82
542408,0,0.72,E,9,7,39,72,B2,Regular,3301,R73
542409,0,0.59,A,7,18,41,106,B1,Regular,26,R24

Export final dataset

In [8]:
df.to_csv("claims_train_final.csv", index=False)

### For the test dataset we will only be removing IDpol as it is a useless measure, we will not be clamping values or removing outliers as we are treating this dataset as real observed data where we would not want to remove data points at will.

In [14]:
df_test = pd.read_csv("claims_test.csv")
df_test = df_test.drop(columns=["IDpol"])
df_test.to_csv("claims_test_final.csv", index=False)